#!/bin/bash

set -e -x

OUTPUT_DIR="${OUTPUT_DIR:?}"

mkdir -p ${OUTPUT_DIR}

pushd cf-riak-cs-release

  git checkout release-candidate

  git rebase develop

popd

cp  -r cf-riak-cs-release ${OUTPUT_DIR}/
