#!/bin/bash

set -eux

: "${ENV_TARGET_FILE:?}"
: "${ENV_METADATA:?}"
MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd ${MY_DIR}/../.. && pwd )"
WORKSPACE_DIR="$( cd ${CI_DIR}/.. && pwd )"
RELEASE_DIR="$( cd ${WORKSPACE_DIR}/cf-riak-cs-release && pwd )"
OUTPUT_DIR="${WORKSPACE_DIR}/${OUTPUT_DIR:?}"
source ${CI_DIR}/scripts/utils.sh

ENV="$(jq_val "env" "${ENV_METADATA}")"
# ensure DEPLOYMENTS_DIR is an absolute path
DEPLOYMENTS_DIR="${DEPLOYMENTS_DIR:?}"
if [[ "${DEPLOYMENTS_DIR}" != /* ]]; then
  DEPLOYMENTS_DIR="${WORKSPACE_DIR}/${DEPLOYMENTS_DIR}"
fi

echo "ENV: ${ENV:?}"

bosh -n target bosh.${ENV}.cf-app.com

echo "args: $*"

pushd ${RELEASE_DIR}
  ./generate_deployment_manifest \
    aws \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/cf/cf-aws-stub.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/cf/cf-networks-stub.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/cf/cf-shared-secrets.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/riak-cs/iaas-settings.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/riak-cs/property-overrides.yml \
    ${DEPLOYMENTS_DIR}/${ENV}/stubs/riak-cs/cf-riak-cs-secrets.yml \
    "$@" > deployment.yml

  cp deployment.yml "${OUTPUT_DIR}/"
  bosh deployment deployment.yml
  cat deployment.yml
popd

echo "Manifest generated successfully"
