#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CI_DIR="$( cd ${MY_DIR}/../.. && pwd )"
WORKSPACE_DIR="$( cd ${CI_DIR}/.. && pwd )"
RELEASE_DIR="$( cd ${WORKSPACE_DIR}/cf-riak-cs-release && pwd )"

OUTPUT_FILE=${OUTPUT_FILE:?}
DOMAIN=$(cat "${BOSH_LITE_METADATA:?}" | jq -r '.domain' )
CF_ADMIN_PASSWORD=$(cat "${BOSH_LITE_METADATA:?}" | jq -r '.cf_password' )
USE_PREVIOUS_RELEASE=${USE_PREVIOUS_RELEASE:-false}

get_version() {
  if [ "${USE_PREVIOUS_RELEASE}" = true ]; then
  echo "$(find ${RELEASE_DIR}/releases/cf-riak-cs-* -type f -printf "%f\n" | \
    cut -d '-' -f3              | \
    cut -d '.' -f1              | \
    sort -n                     | \
    tail -1)"
  else
    echo "latest"
  fi
}

RIAK_STUB="${RELEASE_DIR}/bosh-lite/stub.yml"

# concourse bosh resource will automatically replace the UUID
RIAK_STUB_MODIFIED=/tmp/riak-cs-stub.yml
sed 's/PLACEHOLDER-DIRECTOR-UUID/~/' ${RIAK_STUB} > ${RIAK_STUB_MODIFIED}

RIAK_VERSION="$(get_version)"
CUSTOM_CI_STUB=/tmp/custom-riak-cs-ci-stub.yml
cat <<CI_STUB > ${CUSTOM_CI_STUB}
releases:
- name: cf-riak-cs
  version: ${RIAK_VERSION}
properties:
  domain: ${DOMAIN}
  system_domain: ${DOMAIN}
  app_domains:
  - ${DOMAIN}
  cf:
    admin_password: ${CF_ADMIN_PASSWORD}
CI_STUB

${RELEASE_DIR}/generate_deployment_manifest \
  warden \
  ${RIAK_STUB_MODIFIED} \
  ${CUSTOM_CI_STUB} \
  "$@" > ${WORKSPACE_DIR}/${OUTPUT_FILE}
